[build]
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/placeholder.mobi"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/download"
  to = "/.netlify/functions/index"
  status = 200
  force = true